// Portuguese names, community slang (BR) and search keywords for AJ Classic items.

// Full names used by Brazilian players / the official pt-BR client. Keys are wiki item names.
export const PT_NAMES = {
  'Headdress': 'Cocar',
  'Rare Long Spiked Collar': 'Coleira Longa Rara',
  'Rare Short Spiked Collar': 'Coleira Curta Rara',
  'Rare Long Spiked Wristband': 'Pulseira Longa Rara',
  'Rare Short Spiked Wristband': 'Pulseira Curta Rara',
  'Spiked Collar': 'Coleira Pontuda',
  'Spiked Wristband': 'Pulseira Pontuda',
  'Top Hat': 'Cartola',
  'Fox Hat': 'Chapéu de Raposa',
  'Rare Fox Hat': 'Chapéu de Raposa Raro',
  'Worn Blanket': 'Cobertor Usado',
  'Pirate Hat': 'Chapéu de Pirata',
  'Viking Hat': 'Chapéu Viking',
  'Rare Viking Hat': 'Chapéu Viking Raro',
  'Elf Tail Armor': 'Armadura de Cauda Élfica',
  'Elf Helmet': 'Capacete Élfico',
  'Elf Armor': 'Armadura Élfica',
  'Elf Bracelets': 'Braceletes Élficos',
  'Flower Crown': 'Coroa de Flores',
  'Tiara': 'Tiara',
  'Party Hat': 'Chapéu de Festa',
  'Bow and Arrows': 'Arco e Flechas',
  'Rare Bow and Arrows': 'Arco e Flechas Raro',
  'Head Feather': 'Pena na Cabeça',
  'Sombrero': 'Sombreiro',
  'Gazelle Horns': 'Chifres de Gazela',
  'Skunk Tail': 'Cauda de Gambá',
  'Raccoon Tail': 'Cauda de Guaxinim',
  'Nerd Glasses': 'Óculos de Nerd',
  'Rare Nerd Glasses': 'Óculos de Nerd Raros',
  'Freedom Bands': 'Braçadeiras da Liberdade',
  'Freedom Cape': 'Capa da Liberdade',
  'Freedom Mask': 'Máscara da Liberdade',
  'Angel Wings': 'Asas de Anjo',
  'Butterfly Wings': 'Asas de Borboleta',
  'Homemade Wings': 'Asas Caseiras',
  'Beta Homemade Wings': 'Asas Caseiras Beta',
  'Elegant Butterfly Wings': 'Asas de Borboleta Elegantes',
  'Scarf': 'Cachecol',
  'Jamaaliday Scarf': 'Cachecol Jamaanatal',
  'Candy Cane Socks': 'Meias de Bengala Doce',
  'Designer Skirt': 'Saia de Estilista',
  'Pillbox Hat': 'Chapéu Casquete',
  'Cotton Candy Hat': 'Chapéu de Algodão Doce',
  'Blackout Spiked Collar': 'Coleira Pontuda Preta',
  'Custom Spiked Collar': 'Coleira Pontuda Personalizada',
  'Neon Spiked Collar': 'Coleira Pontuda Neon',
  'Double Spiked Collar': 'Coleira Pontuda Dupla',
  'Double Spiked Wristband': 'Pulseira Pontuda Dupla',
  'Arctic Wolf Hat': 'Chapéu de Lobo Ártico',
  'Bunny Hat': 'Chapéu de Coelho',
  'Wizard Hat': 'Chapéu de Mago',
  'Witch Hat': 'Chapéu de Bruxa',
  'Crown': 'Coroa',
  "King's Crown": 'Coroa de Rei',
  'Knight Helmet': 'Capacete de Cavaleiro',
  'Glove': 'Luva',
  'Spirit Glove': 'Luva Espiritual',
  'Heart Locket': 'Medalhão de Coração',
  'Sparkly Boa': 'Boá Brilhante',
  'Lace Bow': 'Laço de Renda',
  'Double Ribbon Bow': 'Laço de Fita Dupla',
  'Jester Hat': 'Chapéu de Bobo da Corte',
  'Giant Jester Hat': 'Chapéu de Bobo da Corte Gigante',
  'Tennis Rackets': 'Raquetes de Tênis',
  'Den Betas': 'Betas de Toca',
  'Clothing Betas': 'Betas de Roupa',
  'Big Pets': 'Pets Grandes',
  'Small Pets': 'Pets Pequenos',
  'Pet Seal': 'Pet Foca',
  'Pet Groundhog': 'Pet Marmota',
  'Pet Sloth': 'Pet Bicho-preguiça',
  'Pet Otter': 'Pet Lontra',
  'Pet Dove': 'Pet Pomba',
  'Pet Hedgehog': 'Pet Ouriço',
  'Pet Golden Pony': 'Pet Pônei Dourado',
  'Pet Golden Armadillo': 'Pet Tatu Dourado',
  'Pet Golden Bunny': 'Pet Coelho Dourado',
  'Pet Squirrel': 'Pet Esquilo',
  'Pet Mouse': 'Pet Rato',
  'Pet Firefly': 'Pet Vaga-lume',
  'Pet Grasshopper': 'Pet Gafanhoto',
  'Pet Ladybug': 'Pet Joaninha',
  'Pet Mantis': 'Pet Louva-a-deus',
  'Magenta Seal': 'Foca Magenta',
  'Galactic Firefly': 'Vaga-lume Galáctico',
  'Exclusive Pet Phantom': 'Pet Phantom Exclusivo',
  'Pet Phantom (Non-Member)': 'Pet Phantom (Não Membro)',
  'Rare Pet Phantom (Member)': 'Pet Phantom Raro (Membro)',
  "Meagyn's Pet Bear": 'Pet Urso da Meagyn',
  'Count Fabulous Bat': 'Morcego Conde Fabuloso',
  'Count Fabulous Cat': 'Gato Conde Fabuloso',
  'Rare Non-Member Pet Fennec Fox': 'Pet Feneco Raro (Não Membro)',
};

// Slang and alternative spellings Brazilian traders type. Keys are wiki item names; "Name|Variant" targets one color.
export const ALIASES = {
  'Rare Long Spiked Collar': ['longa', 'coleira longa', 'spike longo', 'espinho longo', 'long', 'rare long'],
  'Rare Long Spiked Collar|Black': ['preta longa', 'pl', 'longa preta', 'coleira preta longa', 'pura', 'solid', 'pure', 'black long', 'bl'],
  'Rare Long Spiked Collar|Red': ['vermelha longa', 'longa vermelha'],
  'Rare Short Spiked Collar': ['curta', 'coleira curta', 'spike curto', 'espinho curto', 'short'],
  'Rare Short Spiked Collar|Black': ['preta curta', 'curta preta', 'black short'],
  'Rare Long Spiked Wristband': ['pulseira longa', 'wrist longo', 'long wrist', 'bracelete longo'],
  'Rare Long Spiked Wristband|Black': ['pulseira preta longa', 'black long wrist'],
  'Rare Short Spiked Wristband': ['pulseira curta', 'wrist curto', 'short wrist'],
  'Headdress': ['cocar', 'hd', 'headdress'],
  'Worn Blanket': ['manta', 'cobertor velho', 'wb'],
  'Den Betas': ['beta', 'beta de toca'],
  'Clothing Betas': ['beta', 'beta de roupa'],
  'Top Hat': ['cartola'],
  'Fox Hat': ['chapéu de raposa'],
  'Pet Seal': ['foca'],
};

const COLORS = {
  black: ['preto', 'preta'], red: ['vermelho', 'vermelha'], blue: ['azul', 'azul'], green: ['verde', 'verde'],
  yellow: ['amarelo', 'amarela'], orange: ['laranja', 'laranja'], purple: ['roxo', 'roxa'], pink: ['rosa', 'rosa'],
  white: ['branco', 'branca'], brown: ['marrom', 'marrom'], gray: ['cinza', 'cinza'], grey: ['cinza', 'cinza'],
  silver: ['prata', 'prata'], gold: ['dourado', 'dourada'], golden: ['dourado', 'dourada'], tan: ['bege', 'bege'],
  magenta: ['magenta', 'magenta'], light: ['claro', 'clara'], dark: ['escuro', 'escura'], teal: ['verde-azulado', 'verde-azulada'],
  cyan: ['ciano', 'ciano'], turquoise: ['turquesa', 'turquesa'], lavender: ['lavanda', 'lavanda'], peach: ['pêssego', 'pêssego'],
  cream: ['creme', 'creme'], rainbow: ['arco-íris', 'arco-íris'], default: ['padrão', 'padrão'], hot: ['choque', 'choque'],
  deep: ['intenso', 'intensa'], pastel: ['pastel', 'pastel'], bright: ['vivo', 'viva'], navy: ['marinho', 'marinho'],
  lime: ['limão', 'limão'], mint: ['menta', 'menta'], violet: ['violeta', 'violeta'], rose: ['rosé', 'rosé'],
  classic: ['clássico', 'clássica'], member: ['membro', 'membro'], 'non-member': ['não membro', 'não membro'],
  multicolored: ['multicolorido', 'multicolorida'], colorful: ['colorido', 'colorida'], beige: ['bege', 'bege'],
};
const FEMININE_START = /^(coleira|pulseira|asa|cauda|luva|máscara|armadura|capa|coroa|tiara|cartola|meia|saia|bota|mochila|cadeira|mesa|faixa|pena|manta|pet foca|pet marmota|pet lontra|pet pomba|pet joaninha|braçadeira|guirlanda|gravata|calça|luminária|pelúcia)/i;

export const colorWords = new Set(Object.keys(COLORS).concat(['&', 'and', 'w/', 'with', 'rare', 'item', 'monday', 'rim', 'non', 'beta', 'glitched', 'sea', 'foam', 'sky', 'blood', 'neon', 'plain', 'solid', 'striped', 'spotted', 'eyes', 'eye', 'gem', 'gems', 'lips', 'stripes', 'spots', 'metallic', 'forest', 'ocean', 'land', 'underwater', 'large', 'small', 'original', 'new', 'old', 'version', 'variant', 'lighter', 'darker', 'olive', 'maroon', 'aqua', 'indigo', 'crimson', 'bronze', 'copper', 'chocolate', 'mustard', 'salmon', 'coral', 'ivory', 'charcoal', 'blush', 'sapphire', 'emerald', 'ruby', 'amethyst', 'jade', 'onyx', 'sand', 'lilac', 'fuchsia', 'scarlet', 'tangerine', 'lemon', 'periwinkle', 'blonde', 'ginger', 'snow', 'ice', 'fire', 'shadow']));

export function translateVariant(variant, ptName) {
  if (!variant) return '';
  if (/^rare item monday$/i.test(variant)) return 'RIM (Raro de Segunda)';
  const fem = ptName ? FEMININE_START.test(ptName) : false;
  // "Light Pink" -> "Pink Light" so it translates to "Rosa Claro"
  variant = variant.replace(/\b(Light|Dark|Hot|Deep|Bright|Pastel)\s+([A-Z][a-z]+)\b/g, (m, mod, col) => COLORS[col.toLowerCase()] ? `${col} ${mod}` : m);
  return variant.replace(/[A-Za-z][A-Za-z-]*/g, w => {
    const c = COLORS[w.toLowerCase()];
    if (!c) return w;
    const t = c[fem ? 1 : 0];
    return w[0] === w[0].toUpperCase() ? t[0].toUpperCase() + t.slice(1) : t;
  }).replace(/\band\b/g, 'e').replace(/\bw\//g, 'c/');
}

// word-level dictionary: only used to build search keywords, never shown
const WORDS = {
  hat: 'chapéu', cap: 'boné', helmet: 'capacete', mask: 'máscara', tail: 'cauda', armor: 'armadura', wings: 'asas', wing: 'asa',
  collar: 'coleira', wristband: 'pulseira', bracelet: 'pulseira', bracelets: 'pulseiras', spiked: 'pontuda espinho', long: 'longa longo',
  short: 'curta curto', rare: 'raro rara', necklace: 'colar', amulet: 'amuleto', crown: 'coroa', glasses: 'óculos', bow: 'laço arco',
  scarf: 'cachecol', cape: 'capa', blanket: 'cobertor manta', boots: 'botas', shoes: 'sapatos', socks: 'meias', glove: 'luva',
  gloves: 'luvas', hood: 'capuz', horns: 'chifres', antlers: 'chifres', feather: 'pena', fox: 'raposa', wolf: 'lobo', arctic: 'ártico',
  bunny: 'coelho', cat: 'gato', dog: 'cachorro', dragon: 'dragão', snow: 'neve', star: 'estrela', heart: 'coração', flower: 'flor',
  diamond: 'diamante', giant: 'gigante', pirate: 'pirata', witch: 'bruxa', wizard: 'mago', king: 'rei', queen: 'rainha',
  princess: 'princesa', knight: 'cavaleiro', winter: 'inverno', spring: 'primavera', summer: 'verão', fall: 'outono', eagle: 'águia',
  rug: 'tapete', chair: 'cadeira', table: 'mesa', lamp: 'luminária abajur', plushie: 'pelúcia', pet: 'pet bichinho', phantom: 'fantasma',
  seal: 'foca', mouse: 'rato', firefly: 'vaga-lume', ladybug: 'joaninha', grasshopper: 'gafanhoto', mantis: 'louva-a-deus',
  sloth: 'preguiça', otter: 'lontra', dove: 'pomba', hedgehog: 'ouriço', groundhog: 'marmota', squirrel: 'esquilo', pony: 'pônei',
  golden: 'dourado', skull: 'caveira', tiara: 'tiara', sword: 'espada', shield: 'escudo', skirt: 'saia', dress: 'vestido',
  jacket: 'jaqueta', shirt: 'camisa', sweater: 'suéter', headdress: 'cocar', beta: 'beta', wristbands: 'pulseiras', raccoon: 'guaxinim',
  skunk: 'gambá', tiger: 'tigre', lion: 'leão', bear: 'urso', owl: 'coruja', bat: 'morcego', spider: 'aranha', butterfly: 'borboleta',
  angel: 'anjo', elf: 'elfo élfico', ghost: 'fantasma', pumpkin: 'abóbora', candy: 'doce', cane: 'bengala', party: 'festa', top: 'cartola',
  freedom: 'liberdade', ribbon: 'fita', lace: 'renda', clover: 'trevo', lucky: 'sorte', moon: 'lua', sun: 'sol', ring: 'anel',
  jamaaliday: 'jamaanatal natal', gauntlets: 'manoplas luvas', ancient: 'antigo antiga', ice: 'gelo', statue: 'estátua', crystal: 'cristal',
  tree: 'árvore', window: 'janela', spooky: 'assustador', wall: 'parede', banner: 'faixa bandeira', gingerbread: 'biscoito gengibre',
  royal: 'real realeza', rainbow: 'arco-íris', epic: 'épico', couch: 'sofá', sofa: 'sofá', gold: 'ouro dourado', archway: 'arco',
  garden: 'jardim', jolly: 'alegre', friendship: 'amizade', wild: 'selvagem', birthday: 'aniversário', stone: 'pedra', blackout: 'blackout preto',
  fountain: 'fonte', art: 'arte', lantern: 'lanterna', feline: 'felino', sea: 'mar', head: 'cabeça', cake: 'bolo', leaf: 'folha',
  classic: 'clássico', pig: 'porco', pixelated: 'pixelado', harvest: 'colheita', hair: 'cabelo peruca', fence: 'cerca', costumed: 'fantasiado',
  throne: 'trono', space: 'espaço', fire: 'fogo', stones: 'pedras', cloud: 'nuvem', fantasy: 'fantasia', new: 'novo', panda: 'panda',
  spirit: 'espírito', balloon: 'balão', autumn: 'outono', glitched: 'bugado glitch', wind: 'vento', ghostly: 'fantasmagórico',
  large: 'grande', camp: 'acampamento', jelly: 'geleia gelatina', striped: 'listrado', egg: 'ovo', wood: 'madeira', goat: 'cabra bode',
  chocolate: 'chocolate', cuffs: 'punhos braceletes', streamer: 'serpentina', snake: 'cobra', bag: 'bolsa', starry: 'estrelado',
  grass: 'grama', sand: 'areia', encrusted: 'incrustado', zombie: 'zumbi', cream: 'creme sorvete', sparkling: 'brilhante', team: 'time',
  firework: 'fogos', claws: 'garras', ruby: 'rubi', cozy: 'aconchegante', ribbons: 'fitas', frosted: 'congelado', silly: 'bobo',
  spectacular: 'espetacular', horse: 'cavalo', frog: 'sapo', desk: 'escrivaninha', coat: 'casaco', mystical: 'místico', pool: 'piscina',
  bee: 'abelha', flag: 'bandeira', ferocious: 'feroz', plaque: 'placa', ocean: 'oceano', cloak: 'manto capa', frozen: 'congelado',
  monkey: 'macaco', haunted: 'assombrado', paws: 'patas', flying: 'voador', lights: 'luzes', cupid: 'cupido', double: 'duplo dupla',
  peppermint: 'hortelã', snowflake: 'floco neve', drum: 'tambor', apple: 'maçã', rabbit: 'coelho', sheep: 'ovelha', shark: 'tubarão',
  feathered: 'penas', house: 'casa', daisy: 'margarida', carnival: 'carnaval', mohawk: 'moicano', yeti: 'yeti', lily: 'lírio',
  book: 'livro', books: 'livros', phoenix: 'fênix', floor: 'chão piso', lava: 'lava', sculpture: 'escultura', blueberry: 'mirtilo',
  earrings: 'brincos', box: 'caixa', elegant: 'elegante', coral: 'coral', bird: 'pássaro', gift: 'presente', rock: 'pedra rocha',
  sparkly: 'brilhante', plant: 'planta', pillow: 'travesseiro almofada', sweet: 'doce', reindeer: 'rena', water: 'água',
  best: 'melhores', friends: 'amigos', paw: 'pata', bands: 'faixas braçadeiras', festive: 'festivo', ornament: 'enfeite', hearts: 'corações',
  bouquet: 'buquê', alien: 'alienígena', fur: 'pelo', eclipse: 'eclipse', galaxy: 'galáxia', mat: 'tapete', rings: 'anéis', cotton: 'algodão',
  vanity: 'penteadeira', chest: 'baú', basket: 'cesta', penguin: 'pinguim', pizza: 'pizza', luminous: 'luminoso', small: 'pequeno',
  straw: 'palha', sign: 'placa', corn: 'milho', pot: 'vaso', holly: 'azevinho', band: 'banda', cafe: 'café', slime: 'gosma', horn: 'chifre',
  banana: 'banana', woven: 'trançado', cursed: 'amaldiçoado', egyptian: 'egípcio', pine: 'pinheiro', leprechaun: 'duende',
  backpack: 'mochila', wreath: 'guirlanda', monster: 'monstro', coal: 'carvão', charm: 'pingente', treasure: 'tesouro', lunar: 'lunar',
  floral: 'floral', scarecrow: 'espantalho', gown: 'vestido', stool: 'banco', medieval: 'medieval', antennae: 'antenas', slippers: 'pantufas',
  turtle: 'tartaruga', lightning: 'raio', shelf: 'prateleira', bush: 'arbusto', rhino: 'rinoceronte', suit: 'terno', guitar: 'guitarra violão',
  unicorn: 'unicórnio', snowman: 'boneco neve', mirror: 'espelho', abstract: 'abstrato', mushroom: 'cogumelo', cookie: 'biscoito',
  cupcake: 'cupcake bolinho', ninja: 'ninja', samurai: 'samurai', viking: 'viking', cowboy: 'caubói', sombrero: 'sombreiro', fedora: 'chapéu',
  beanie: 'gorro', beret: 'boina', bonnet: 'touca', halo: 'auréola', fairy: 'fada', faerie: 'fada', mermaid: 'sereia',
  whale: 'baleia', dolphin: 'golfinho', octopus: 'polvo', crab: 'caranguejo', fish: 'peixe', jellyfish: 'água-viva', seahorse: 'cavalo-marinho',
  elephant: 'elefante', giraffe: 'girafa', zebra: 'zebra', koala: 'coala', kangaroo: 'canguru', deer: 'cervo', moose: 'alce', llama: 'lhama',
  cheetah: 'guepardo', leopard: 'leopardo', hyena: 'hiena', wolfs: 'lobos', puppy: 'filhote cachorro', kitty: 'gatinho', duck: 'pato',
  chicken: 'galinha', turkey: 'peru', parrot: 'papagaio', peacock: 'pavão', flamingo: 'flamingo', toucan: 'tucano', hummingbird: 'beija-flor',
  tie: 'gravata', bowtie: 'gravata borboleta', vest: 'colete', pants: 'calça', shorts: 'shorts', belt: 'cinto', purse: 'bolsa',
  umbrella: 'guarda-chuva', parasol: 'sombrinha', staff: 'cajado', wand: 'varinha', bone: 'osso', bones: 'ossos', tooth: 'dente',
  teeth: 'dentes', fang: 'presa', beard: 'barba', moustache: 'bigode', mustache: 'bigode', pigtails: 'marias-chiquinhas', braid: 'trança',
  locket: 'medalhão', pendant: 'pingente', lei: 'colar havaiano', boa: 'boá', ruff: 'gola', fluff: 'pelúcia', anklet: 'tornozeleira',
  heels: 'salto', sneakers: 'tênis', skates: 'patins', flippers: 'nadadeiras', fin: 'barbatana', shell: 'concha casco', pearl: 'pérola',
  jewel: 'joia', gem: 'joia gema', emerald: 'esmeralda', sapphire: 'safira', amethyst: 'ametista', topaz: 'topázio', plushies: 'pelúcias',
  television: 'televisão', clock: 'relógio', bed: 'cama', bench: 'banco', stairs: 'escada', door: 'porta', gate: 'portão', bridge: 'ponte',
  tent: 'barraca', torch: 'tocha', candle: 'vela', candles: 'velas', fireplace: 'lareira', piano: 'piano', telescope: 'telescópio',
  bookshelf: 'estante', wardrobe: 'guarda-roupa', dresser: 'cômoda', rocket: 'foguete', robot: 'robô', castle: 'castelo', tower: 'torre',
  volcano: 'vulcão', waterfall: 'cachoeira', palm: 'palmeira', cactus: 'cacto', tulip: 'tulipa', sunflower: 'girassol',
  sunflowers: 'girassóis', petunias: 'petúnias', vine: 'trepadeira', vines: 'trepadeiras', web: 'teia', cauldron: 'caldeirão', broom: 'vassoura',
  potion: 'poção', spell: 'feitiço', spells: 'feitiços', trick: 'doces travessuras', treat: 'doce', present: 'presente', stocking: 'meia natal',
  sleigh: 'trenó', santa: 'papai noel', valentine: 'namorados', clown: 'palhaço', jester: 'bobo',
  musketeer: 'mosqueteiro', astronaut: 'astronauta', chef: 'chef cozinheiro', doctor: 'médico', police: 'polícia', firefighter: 'bombeiro',
  sailor: 'marinheiro', captain: 'capitão', army: 'exército', soldier: 'soldado', warrior: 'guerreiro', gladiator: 'gladiador', spartan: 'espartano',
};
export function searchKeywords(text) {
  const out = new Set();
  for (const w of text.toLowerCase().split(/[^a-z-]+/)) {
    if (WORDS[w]) WORDS[w].split(' ').forEach(x => out.add(x));
    if (COLORS[w]) COLORS[w].forEach(x => out.add(x));
  }
  return [...out].join(' ');
}
